app/my_library/forms/BookForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Optional, Length


class BookForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(max=255), Optional(strip_whitespace=True)])
    author = StringField("Author", validators=[DataRequired(), Length(max=64), Optional(strip_whitespace=True)])
    submit = SubmitField("Save")

app/my_library/forms/BookLibForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField, TextAreaField
from wtforms.validators import DataRequired, Length, Optional, ValidationError
from datetime import date


class BookLibForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(max=255), Optional(strip_whitespace=True)])
    author = StringField("Author", validators=[DataRequired(), Length(max=64), Optional(strip_whitespace=True)])
    isbn = StringField("ISBN", validators=[DataRequired(), Length(max=16), Optional(strip_whitespace=True)])
    purch_date = DateField("Purchase Date", default=date.today, format="%m/%d/%Y")
    notes = TextAreaField("Notes", validators=[Length(max=1024), Optional(strip_whitespace=True)])
    submit = SubmitField("Save")

    def validate_isbn(self, isbn):
        if not isbn.data.isnumeric():
            raise ValidationError("The ISBN is invalid or is not numeric")

app/my_library/forms/LibEntryForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, DateField, TextAreaField
from wtforms.validators import Length
from datetime import date


class LibEntryForm(FlaskForm):
    purch_date = DateField("Purchase Date", default=date.today, format="%m/%d/%Y")
    notes = TextAreaField("Notes", validators=[Length(max=1024)])
    submit = SubmitField("Save")

app/my_library/forms/ShareLibraryForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email, Optional


class ShareLibraryForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email(), Optional(strip_whitespace=True)])
    send = SubmitField("Send")

app/my_library/__init__.py
from flask import Blueprint

bp = Blueprint("my_library", __name__)

from app.my_library import routes

app/my_library/routes.py
from app.my_library import bp
from app import db

from flask import render_template, flash, redirect, url_for, current_app
from flask_login import current_user, login_required
from datetime import datetime

from app.email.email import send_mail

from app.my_library.forms.BookLibForm import BookLibForm
from app.my_library.forms.LibEntryForm import LibEntryForm
from app.my_library.forms.BookForm import BookForm
from app.my_library.forms.ShareLibraryForm import ShareLibraryForm

from app.models.Book import Book
from app.models.UserBooks import UserBooks
from app.models.User import User


@bp.route("/")
def index():
    return render_template(
        "my_library/index.html",
        title="Welcome!"
    )


@bp.route("/library")
@login_required
def summary():
    lib = UserBooks.query.join(Book).join(User).filter_by(id=current_user.id).all()

    return render_template(
        "my_library/lib_summary.html",
        title="My Library",
        lib=lib
    )


@bp.route("/library/books/add", methods=["GET", "POST"])
@bp.route("/library/books/add/<int:book_id>", methods=["GET"])
@login_required
def add_book_to_lib(book_id=None):
    if book_id:
        book = Book.query.filter_by(id=book_id).first()

        if not book:
            flash("This book doesn't exist!", category="error")
            return redirect(url_for("my_library.summary"))

        if book in current_user.books:
            flash("This book is already in your library!", category="info")
            return redirect(url_for("my_library.book_list"))

        library_meta = UserBooks(
            purch_date=datetime.now(),
            book=book,
            user=current_user
        )

        db.session.add(library_meta)
        db.session.commit()

        return redirect(url_for("my_library.edit_lib_entry", book_id=book.id))

    form = BookLibForm()

    if form.validate_on_submit():
        add_msg = "{} has been added to your library!".format(form.title.data)

        book = Book.query.filter_by(isbn=form.isbn.data).first()
        if book is not None:
            add_msg = "A book matching ISBN {} was found. Adding it to your library!".format(form.isbn.data)
        else:
            book = Book(
                title=form.title.data,
                author=form.author.data,
                isbn=form.isbn.data
            )

        db.session.add(book)
        db.session.commit()

        library_meta = UserBooks.query.filter_by(user_id=current_user.id, book_id=book.id).first()
        if library_meta is None:
            library_meta = UserBooks(
                purch_date=form.purch_date.data,
                notes=form.notes.data,
                book=book,
                user=current_user
            )

            db.session.add(library_meta)
            db.session.commit()

            flash(add_msg, category="info")

        return redirect(url_for("my_library.summary"))

    return render_template(
        "my_library/add_book_to_lib.html",
        title="Add a Book to Your Library",
        form=form
    )


@bp.route("/library/books/delete/<int:book_id>", methods=["GET", "DELETE"])
@login_required
def del_book_from_lib(book_id):
    book = Book.query.filter_by(id=book_id).first()
    if book:
        current_user.books.remove(book)
        db.session.commit()
        flash("Entry for {} removed from your library!".format(book.title), category="info")

    return redirect(url_for("my_library.summary"))


@bp.route("/library/books/edit/<int:book_id>", methods=["GET", "POST"])
@login_required
def edit_lib_entry(book_id):
    book = Book.query.filter_by(id=book_id).first()
    lib_entry = UserBooks.query.filter_by(user_id=current_user.id, book_id=book_id).first()

    if lib_entry is None or book is None:
        return redirect(url_for("my_library.summary"))

    form = LibEntryForm()

    if form.validate_on_submit():
        lib_entry.purch_date = form.purch_date.data
        lib_entry.notes = form.notes.data
        db.session.commit()

        flash("Library entry for {} updated!".format(book.title), category="info")
        return redirect(url_for("my_library.summary"))

    form.purch_date.data = lib_entry.purch_date
    form.notes.data = lib_entry.notes

    return render_template(
        "my_library/edit_library_entry.html",
        title="Edit Your Library Entry",
        form=form,
        book=book
    )


@bp.route("/books")
@login_required
def book_list():
    books = Book.query.all()

    return render_template(
        "my_library/all_books.html",
        title="All Books",
        books=books
    )


@bp.route("/books/edit/<int:book_id>", methods=["GET", "POST"])
@login_required
def edit_book(book_id):
    book = Book.query.filter_by(id=book_id).first()

    if book is None:
        return redirect(url_for("my_library.summary"))

    form = BookForm()

    if form.validate_on_submit():
        book.title = form.title.data
        book.author = form.author.data
        db.session.commit()

        flash("Book entry for ISBN {} updated!".format(book.isbn), category="info")
        return redirect(url_for("my_library.summary"))

    form.title.data = book.title
    form.author.data = book.author

    return render_template(
        "my_library/edit_book.html",
        title="Edit Book",
        form=form,
        book=book
    )


@bp.route("/library/share", methods=["GET", "POST"])
@login_required
def share_library():
    form = ShareLibraryForm()

    if form.validate_on_submit():
        lib = UserBooks.query.join(Book).join(User).filter_by(id=current_user.id).all()

        send_mail(
            subject="My Python Library: Shared Library",
            sender=current_app.config['ADMIN'],
            recipients=[form.email.data],
            txt_body=render_template(
                "email/share_library_email.txt",
                lib=lib,
                recipient=form.email.data,
                user_email=current_user.email
            ),
            html_body=render_template(
                "email/share_library_email.html",
                lib=lib,
                recipient=form.email.data,
                user_email=current_user.email
            )
        )

        flash("Your library has been shared with {}!".format(form.email.data), category="info")
        return redirect(url_for("my_library.summary"))

    return render_template(
        "my_library/share_library.html",
        title="Share Your Library",
        form=form
    )

app/templates/my_library/add_book_to_lib.html
{% extends "app_shell.html" %}

{% block content %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <span class="add-book-to-lib-form-full-row">
        {{ form.title.label }}
        {{ form.title(size=64) }}
    </span>
    <span class="add-book-to-lib-form-full-row">
        {{ form.author.label }}
        {{ form.author(size=64) }}
    </span>
    <span class="add-book-to-lib-form-inline-row">
        {{ form.isbn.label }}
        {{ form.isbn(size=16) }}
    </span>
    <span class="add-book-to-lib-form-inline-row">
        {{ form.purch_date.label }}
        {{ form.purch_date() }}
    </span>
    <span class="add-book-to-lib-form-full-row">
        {{ form.notes.label }}
        {{ form.notes(cols=32, rows=4) }}
    </span>
    <span class="form-info-messages">
        {% for error in form.title.errors %}
        <span class="form-error error"><b>Title:</b> {{ error }}</span>
        {% endfor %}
        {% for error in form.author.errors %}
        <span class="form-error error"><b>Author:</b> {{ error }}</span>
        {% endfor %}
        {% for error in form.isbn.errors %}
        <span class="form-error error"><b>ISBN:</b> {{ error }}</span>
        {% endfor %}
        {% for error in form.purch_date.errors %}
        <span class="form-error error"><b>Purchase Date:</b> {{ error }}</span>
        {% endfor %}
        {% for error in form.notes.errors %}
        <span class="form-error error"><b>Notes:</b> {{ error }}</span>
        {% endfor %}
    </span>
    <span>{{ form.submit() }}</span>

</form>
{% endblock %}

app/templates/my_library/add_edit_book.html
{% extends "app_shell.html" %}

{% block content %}
    <h1>Add/Edit Book</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br/>
            {{ form.title(size=64) }}
            {% for error in form.title.errors %}
                <span class="form-error">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.author.label }}<br/>
            {{ form.author(size=64) }}
            {% for error in form.author.errors %}
                <span class="form-error">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.isbn.label }}<br/>
            {{ form.isbn(size=16) }}
            {% for error in form.isbn.errors %}
                <span class="form-error">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.purch_date.label }}<br/>
            {{ form.purch_date() }}
            {% for error in form.purch_date.errors %}
                <span class="form-error">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.notes.label }}<br/>
            {{ form.notes(cols=32, rows=4) }}
            {% for error in form.notes.errors %}
                <span class="form-error">{{ error }}</span>
            {% endfor %}
        </p>

        <p>{{ form.submit() }}</p>
    </form>


{% endblock %}

app/templates/my_library/all_books.html
{% extends "app_shell.html" %}

{% block content %}
{% if books %}
    <ul class="book-list-summary">
        {% for book in books %}
            <li>
                <span class="book-list-title">{{ book.title }}</span>
                <span class="book-list-author">By {{ book.author }}</span>
                <span class=book-list-isbn><b>ISBN</b> {{ book.isbn }}</span>
                <span class="book-list-links">
                    <a href="{{ url_for('my_library.edit_book', book_id=book.id) }}">Edit book</a> |
                    <a href="{{ url_for('my_library.add_book_to_lib', book_id=book.id) }}">Add to my library</a>
                </span>
            </li>
        {% endfor %}
    </ul>
{% else %}
<h4>No one has added any books yet</h4>
<p>
    Maybe yours can be the first! Click <a href="{{ url_for('my_library.add_book_to_lib') }}">ADD BOOK TO LIBRARY</a>
    to get started.
</p>
{% endif %}
{% endblock %}

app/templates/my_library/edit_book.html
{% extends "app_shell.html" %}

{% block content %}
<h4>{{ book.title }} by {{ book.author }}</h4>
<h6>ISBN {{ book.isbn }}</h6>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.title.label }}
        {{ form.title() }}
    </p>
    <p>
        {{ form.author.label }}
        {{ form.author() }}

    </p>
    <span class="form-info-messages">
        {% for error in form.title.errors %}
        <span class="form-error"><b>Title:</b> {{ error }}</span>
        {% endfor %}
        {% for error in form.author.errors %}
        <span class="form-error"><b>Author:</b> {{ error }}</span>
        {% endfor %}
    </span>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/my_library/edit_library_entry.html
{% extends "app_shell.html" %}

{% block content %}
<h4>{{ book.title }} by {{ book.author }}</h4>
<h6>ISBN {{ book.isbn }}</h6>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.purch_date.label }}
        {{ form.purch_date() }}
    </p>
    <p>
        {{ form.notes.label }}
        {{ form.notes(cols=32, rows=4) }}
    </p>
    <span class="form-info-messages">
        {% for error in form.purch_date.errors %}
            <span class="form-error error"><b>Purchase Date:</b> {{ error }}</span>
        {% endfor %}
        {% for error in form.notes.errors %}
            <span class="form-error error"><b>Notes:</b> {{ error }}</span>
        {% endfor %}
    </span>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/my_library/index.html
{% extends "app_shell.html" %}

{% block content %}
<h4>This is a personal library application written in Python and Flask</h4>
<p>
   Created for the PSC Web Developer Flask Programming Project by Dusty Williams
</p>
{% endblock %}

app/templates/my_library/lib_summary.html
{% extends "app_shell.html" %}

{% block content %}
<p>
    Click <a href="{{ url_for('my_library.add_book_to_lib') }}">ADD BOOK TO LIBRARY</a> to add a new book to your
    library. This will add the book to the global book list so other users can add the book to their libraries, too. Or,
    click <a href="{{ url_for('my_library.book_list') }}">ALL BOOKS</a> to see books other users have added and add one
    to your own library.
</p>
{% if lib %}
<ul class="book-list-summary">
    {% for entry in lib %}
    <li>
        <span class="book-list-title">{{ entry.book.title }}</span>
        <span class="book-list-author">By {{ entry.book.author }}</span>
        <span class="book-list-isbn"><b>ISBN</b> {{ entry.book.isbn }}</span>
        {% if entry.purch_date %}
        <span class="book-list-purch-date"><b>Date Purchased:</b> {{ entry.purch_date }}</span>
        {% endif %}
        {% if entry.notes %}
            <span class="book-list-notes"><b>Notes:</b> {{ entry.notes }}</span>
        {% endif %}
        <span class="book-list-links">
            <a href="{{ url_for('my_library.del_book_from_lib', book_id=entry.book.id) }}">Remove from my library</a> |
            <a href="{{ url_for('my_library.edit_lib_entry', book_id=entry.book.id) }}">Edit library entry</a>
        </span>
    </li>
    {% endfor %}
</ul>
<p>
    <a class="looks-like-a-button" href="{{ url_for('my_library.share_library') }}">Share Library</a>
</p>
{% else %}
<h4>Your library is currently empty!</h4>
{% endif %}
{% endblock %}

app/templates/my_library/share_library.html
{% extends "app_shell.html" %}

{% block content %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.email.label }}
        {{ form.email(size=64) }}
    </p>

    <span class="form-info-messages">
        {% for error in form.email.errors %}
        <span class="form-error error"><b>Email:</b> {{ error }}</span>
        {% endfor %}
    </span>

    <p>{{ form.send() }}</p>
</form>
{% endblock %}